In [11]:
import pandas as pd
Data = pd.read_csv("https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv",encoding = "latin-1")
print(Data.head())
Data.groupby('Element').sum()

   Area Code     Area  Item Code         Item  Element Code  \
0          4  Algeria       2501   Population           511
1          4  Algeria       2501   Population          5301
2          4  Algeria       2901  Grand Total           664
3          4  Algeria       2901  Grand Total           674
4          4  Algeria       2901  Grand Total           684

                                  Element             Unit     Y2014  \
0           Total Population - Both sexes     1000 persons  38924.00
1                Domestic supply quantity      1000 tonnes      0.00
2           Food supply (kcal/capita/day)  kcal/capita/day   3377.00
3  Protein supply quantity (g/capita/day)     g/capita/day     94.90
4      Fat supply quantity (g/capita/day)     g/capita/day     80.06

      Y2015     Y2016     Y2017     Y2018
0  39728.00  40551.00  41389.00  42228.00
1      0.00      0.00      0.00      0.00
2   3379.00   3372.00   3341.00   3322.00
3     94.35     94.72     92.82     91.83
4     79.36     77.40     80.19     77.28

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [36]:
Data.groupby([Data['Area']!='Madagascar', 'Element']).sum()

                                              Area Code  Item Code  \
Area  Element
False Domestic supply quantity                    15351     318888
      Export Quantity                             13416     279445
      Fat supply quantity (g/capita/day)          14319     299405
      Feed                                         4515      94030
      Food                                        14190     295817
      Food supply (kcal/capita/day)               14319     299405
      Food supply quantity (kg/capita/yr)         14190     295817
      Import Quantity                             14319     297945
      Losses                                       7095     148102
      Other uses (non-food)                        6579     138246
      Processing                                   9804     201929
      Production                                  14190     295071
      Protein supply quantity (g/capita/day)      14319     299405
      Residuals                                   13545     280011
      Seed                                         2709      56067
      Stock Variation                             12642     262174
      Total Population - Both sexes                 129       2501
True  Domestic supply quantity                   693642   13878557
      Export Quantity                            586494   11561108
      Fat supply quantity (g/capita/day)         660731   13235595
      Feed                                       171757    3444477
      Food                                       649105   12989218
      Food supply (kcal/capita/day)              659738   13211655
      Food supply quantity (kg/capita/yr)        644256   12889584
      Import Quantity                            673855   13498021
      Losses                                     267258    5276701
      Other uses (non-food)                      228975    4591503
      Processing                                 262136    5148487
      Production                                 512561   10154982
      Protein supply quantity (g/capita/day)     660731   13235595
      Residuals                                  609726   12141078
      Seed                                       100828    1979866
      Stock Variation                            558924   11067353
      Total Population - Both sexes                5891     110044
      Tourist consumption                         50308    1486528

                                              Element Code       Y2014  \
Area  Element
False Domestic supply quantity                      630819    31578.76
      Export Quantity                               614744      425.48
      Fat supply quantity (g/capita/day)             75924       88.72
      Feed                                          193235     2178.76
      Food                                          565620    21405.42
      Food supply (kcal/capita/day)                  73704     7945.00
      Food supply quantity (kg/capita/yr)            70950      907.59
      Import Quantity                               622821     2010.71
      Losses                                        281765     2252.00
      Other uses (non-food)                         262854     4348.58
      Processing                                    389956     1262.00
      Production                                    606210    30337.51
      Protein supply quantity (g/capita/day)         74814      177.79
      Residuals                                     542850     -603.00
      Seed                                          116067      728.00
      Stock Variation                               497056      352.00
      Total Population - Both sexes                    511    23590.00
True  Domestic supply quantity                    27437976  1965137.59
      Export Quantity                             25411389   149595.16
      Fat supply quantity (g/capita/day)           3359808    10136.84
      Feed                                         7088964   214749.13
      Food                                        24841002  1190927.07
      Food supply (kcal/capita/day)                3255592   446312.00
      Food supply quantity (kg/capita/yr)          3092775    48743.04
      Import Quantity                             28212108   272133.77
      Losses                                      10010342   150971.00
      Other uses (non-food)                        8663874    74369.55
      Processing                                   9923354   281661.00
      Production                                  20781981  1900950.24
      Protein supply quantity (g/capita/day)       3310688    11658.67
      Residuals                                   23523500    30752.00
      Seed                                         4095507    21194.92
      Stock Variation                             20967648    58397.83
      Total Population - Both sexes                  22484  1007995.00
      Tourist consumption                          2869905      416.00

                                                   Y2015       Y2016  \
Area  Element
False Domestic supply quantity                  31214.98    31732.08
      Export Quantity                             494.75      535.06
      Fat supply quantity (g/capita/day)           91.85       95.33
      Feed                                       2070.22     2121.40
      Food                                      21120.65    21435.61
      Food supply (kcal/capita/day)              7685.00     7669.00
      Food supply quantity (kg/capita/yr)         871.59      861.17
      Import Quantity                            1721.80     1901.47
      Losses                                     2176.00     2215.00
      Other uses (non-food)                      3957.12     4114.08
      Processing                                 1803.00     1770.00
      Production                                29482.89    29889.65
      Protein supply quantity (g/capita/day)      173.05      173.40
      Residuals                                  -616.00     -642.00
      Seed                                        699.00      720.00
      Stock Variation                            -505.00     -475.00
      Total Population - Both sexes             24234.00    24894.00
True  Domestic supply quantity                1990278.57  2013110.62
      Export Quantity                          157119.72   151385.40
      Fat supply quantity (g/capita/day)        10143.89    10007.44
      Feed                                     222980.00   226837.25
      Food                                    1211240.45  1225586.56
      Food supply (kcal/capita/day)            445698.00   444141.00
      Food supply quantity (kg/capita/yr)       48473.54    48124.11
      Import Quantity                          265296.66   284681.31
      Losses                                   153263.00   155572.00
      Other uses (non-food)                     62297.29    65449.60
      Processing                               286126.00   278861.00
      Production                              1917536.50  1913647.50
      Protein supply quantity (g/capita/day)    11660.90    11606.29
      Residuals                                 30661.00    37866.00
      Seed                                      23277.82    22669.20
      Stock Variation                           35415.99    33615.12
      Total Population - Both sexes           1033847.00  1060213.00
      Tourist consumption                         349.00       89.00

                                                   Y2017       Y2018
Area  Element
False Domestic supply quantity                  31927.87    32596.87
      Export Quantity                             566.81      535.81
      Fat supply quantity (g/capita/day)          101.03       96.43
      Feed                                       2059.60     2133.60
      Food                                      21676.21    22116.21
      Food supply (kcal/capita/day)              7768.00     7748.00
      Food supply quantity (kg/capita/yr)         847.75      842.17
      Import Quantity                            3139.79     3214.79
      Losses                                     2153.00     2253.00
      Other uses (non-food)                      4170.06     4221.06
      Processing                                 1826.00     1819.00
      Production                                29267.86    30215.86
      Protein supply quantity (g/capita/day)      175.75      176.64
      Residuals                                  -657.00     -676.00
      Seed                                        695.00      728.00
      Stock Variation                             -91.00      293.00
      Total Population - Both sexes             25571.00    26262.00
True  Domestic supply quantity                2056270.23  2128595.23
      Export Quantity                          181771.99   181058.99
      Fat supply quantity (g/capita/day)        10152.81    10162.26
      Feed                                     221646.08   231356.08
      Food                                    1237212.07  1281725.07
      Food supply (kcal/capita/day)            446913.00   447513.00
      Food supply quantity (kg/capita/yr)       47842.29    48214.68
      Import Quantity                          291419.30   284782.30
      Losses                                   158461.00   161649.00
      Other uses (non-food)                     87475.91    87079.91
      Processing                               291010.00   306610.00
      Production                              2000789.03  2044857.03
      Protein supply quantity (g/capita/day)    11666.70    11656.92
      Residuals                                 36157.00    35540.00
      Seed                                      24175.14    24535.14
      Stock Variation                           54407.91    20284.91
      Total Population - Both sexes           1087070.00  1114343.00
      Tourist consumption                          91.00       90.00

In [42]:
y = [(2, 4), (7, 8), (1, 5, 9)]
print(y[1][1])

8

In [43]:
Data.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [44]:
Data.shape

(60943, 12)

In [45]:
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [46]:
Data.groupby(['Item']).sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,
"Alcohol, Non-Food",38447,752497,1515090,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,75016,1649136,2171381,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,18060,397035,90990,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,85279,1882494,2567303,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,69280,1352989,1920418,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...
"Vegetables, Other",77779,1518715,2275409,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,18060,391905,90990,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,87073,1639683,2654934,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,66206,1319535,1818328,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,50798,970905,1525745,200396.96,203151.78,220626.20,229174.59,221272.09

In [51]:
x= Data.groupby(['Area']).sum()
x.sort_values(by=['Y2017'], ascending=False)

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,
Nigeria,234366,3954357,5726937,1399542.19,1414362.83,1482945.71,1483268.23,1499774.24
Egypt,87792,3996567,5893126,849192.30,868218.73,858568.63,866379.92,852652.92
South Africa,282598,3759379,5450983,497289.52,468352.18,462224.16,517590.54,509787.97
Ethiopia,344386,3878162,5598223,415935.50,429139.33,444567.57,448683.76,450788.86
Morocco,199199,3743082,5414999,375977.76,412473.80,367884.18,388495.36,399271.27
Ghana,109674,3639339,5135536,308328.59,311092.13,314320.45,337599.06,358915.64
Algeria,5252,3532053,5017927,313375.33,324058.40,326007.41,325644.27,341729.98
United Republic of Tanzania,305085,3809549,5461092,337430.64,341969.46,333765.86,322616.85,349763.41
Kenya,177840,4185637,6211860,255211.01,265506.19,260257.56,264660.66,270916.80
Sudan,363216,3534661,4866583,247577.56,230652.54,253197.29,239931.92,268054.39
Cameroon,46720,3916078,5663196,217630.28,225220.72,231714.36,232030.43,233022.93
Angola,9968,3819908,5515088,208584.42,209565.67,214725.32,229159.57,235206.68
Côte d'Ivoire,156969,3934818,5691192,195982.84,211591.29,211439.20,224599.01,227018.00
Uganda,329508,3909109,5660301,218142.33,220615.72,202981.34,213950.38,222147.25
Malawi,188110,3879389,5600952,173454.86,167989.09,164970.42,181098.71,187366.09
Mozambique,205488,3830309,5566682,160757.87,158231.17,159924.41,161407.98,164934.05
Mauritania,162520,3222107,4297253,109557.63,61909.99,79872.42,156665.46,157479.95
Mali,171969,3469876,4878889,123038.75,132456.58,147324.78,149928.33,159026.42
Madagascar,185631,3864258,5619900,128985.32,126674.90,129010.25,131197.73,134576.44
Niger,221674,3763737,5384208,108236.65,117834.65,123601.88,126707.58,133982.86
Benin,68105,3453692,4852820,118050.79,108181.13,117963.59,124771.22,124960.70
Tunisia,297036,3602818,5131662,117029.33,128211.41,123778.86,124167.20,127343.17
Zambia,364201,3892801,5638889,99318.53,96214.00,97728.69,103223.77,101604.27
Burkina Faso,328297,3778795,5431243,105051.33,102701.22,107702.27,101855.07,112970.72
Guinea,126900,3782145,5431286,91213.40,92803.39,95450.24,98138.87,103262.08
Senegal,285090,3922180,5643618,78533.93,91939.14,89017.72,95681.15,95493.82
Zimbabwe,252133,3739292,5346770,78366.34,74041.79,75638.88,75919.34,76581.41
Rwanda,262384,3824085,5477860,70001.38,70138.83,70921.76,73663.69,74839.08
Chad,52377,3606529,5108355,65940.17,65835.88,72673.76,71594.68,72282.24
Sierra Leone,244674,3343306,4603040,62570.89,62523.14,52767.72,55311.33,55981.73
Eswatini,268356,3456174,4870226,53285.75,54072.07,54025.21,54343.33,55045.07
Mauritius,188786,3711587,5317897,50898.12,53372.42,49272.41,51114.83,47150.91
Togo,280798,3478828,4868747,47618.05,47834.59,47930.75,49841.88,54872.00
Congo,64998,3792029,5445560,38699.26,40255.51,40592.66,41181.68,42005.53
Central African Republic,49728,3607546,5069094,28739.02,28885.34,29454.54,29937.00,30101.57
Namibia,188601,3452725,4813630,32026.42,30687.90,30389.07,29874.89,29350.04
Liberia,148338,3249929,4309057,27898.35,28698.10,29746.68,29342.20,29629.83
Gabon,92130,3354410,4590308,28126.31,28367.30,28129.95,27979.64,28339.38
Gambia,87600,3145402,4272295,19607.87,19665.39,21758.15,23154.18,23513.80
Djibouti,78840,2956078,3980378,21332.28,23690.16,21783.91,22729.91,23718.96
Botswana,27560,3704902,5259784,22339.92,23024.85,22970.65,22101.30,23129.08
Lesotho,140300,3099348,4204994,19125.89,17965.84,17258.96,21267.96,19109.23
Guinea-Bissau,197400,3035574,4011694,17708.67,17990.06,18524.83,19102.77,18997.92
Cabo Verde,44100,3396746,4787751,14576.94,14538.93,14569.40,14650.74,14622.60
Sao Tome and Principe,227161,3168050,4260866,12458.64,12386.93,12647.56,12662.63,12806.49
Seychelles,13328,188266,367816,305.20,358.20,416.32,442.34,442.34
Comoros,2025,124514,241681,32.00,41.34,54.91,59.84,59.84
Sudan (former),10918,146631,286940,0.00,0.00,0.00,0.00,0.00
Ethiopia PDR,2418,107853,209609,0.00,0.00,0.00,0.00,0.00

In [52]:
S = [['him', 'sell'], [90, 28, 43]]
print(S[0][1][1])

e

In [67]:
x= Data['Y2014'].isnull().sum()
print(x)
y = Data['Y2014'].count()
print(round((x/y)*100,3))

1589
2.677

In [71]:
print(Data['Area'].unique().size)

49

In [73]:
Data.groupby(['Element']).sum()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,
Domestic supply quantity,708993,14197445,28068795,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,599910,11840553,26026133,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),675050,13535000,3435732,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,176272,3538507,7282199,216927.89,225050.22,228958.65,223705.68,233489.68
Food,663295,13285035,25406622,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),674057,13511060,3329296,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),658446,13185401,3163725,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,688174,13795966,28834929,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,274353,5424803,10292107,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),235554,4729749,8926728,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,271940,5350416,10313310,282923.00,287929.00,280631.00,292836.00,308429.00
Production,526751,10450053,21388191,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),675050,13535000,3385502,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,623271,12421089,24066350,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,103537,2035933,4211574,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,571566,11329527,21464704,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,6020,112545,22995,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,50308,1486528,2869905,416.00,349.00,89.00,91.00,90.00

In [74]:
x= Data.groupby(['Area']).sum()
x.sort_values(by=['Y2017'], ascending=True)

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,
Sudan (former),10918,146631,286940,0.00,0.00,0.00,0.00,0.00
Ethiopia PDR,2418,107853,209609,0.00,0.00,0.00,0.00,0.00
Comoros,2025,124514,241681,32.00,41.34,54.91,59.84,59.84
Seychelles,13328,188266,367816,305.20,358.20,416.32,442.34,442.34
Sao Tome and Principe,227161,3168050,4260866,12458.64,12386.93,12647.56,12662.63,12806.49
Cabo Verde,44100,3396746,4787751,14576.94,14538.93,14569.40,14650.74,14622.60
Guinea-Bissau,197400,3035574,4011694,17708.67,17990.06,18524.83,19102.77,18997.92
Lesotho,140300,3099348,4204994,19125.89,17965.84,17258.96,21267.96,19109.23
Botswana,27560,3704902,5259784,22339.92,23024.85,22970.65,22101.30,23129.08
Djibouti,78840,2956078,3980378,21332.28,23690.16,21783.91,22729.91,23718.96
Gambia,87600,3145402,4272295,19607.87,19665.39,21758.15,23154.18,23513.80
Gabon,92130,3354410,4590308,28126.31,28367.30,28129.95,27979.64,28339.38
Liberia,148338,3249929,4309057,27898.35,28698.10,29746.68,29342.20,29629.83
Namibia,188601,3452725,4813630,32026.42,30687.90,30389.07,29874.89,29350.04
Central African Republic,49728,3607546,5069094,28739.02,28885.34,29454.54,29937.00,30101.57
Congo,64998,3792029,5445560,38699.26,40255.51,40592.66,41181.68,42005.53
Togo,280798,3478828,4868747,47618.05,47834.59,47930.75,49841.88,54872.00
Mauritius,188786,3711587,5317897,50898.12,53372.42,49272.41,51114.83,47150.91
Eswatini,268356,3456174,4870226,53285.75,54072.07,54025.21,54343.33,55045.07
Sierra Leone,244674,3343306,4603040,62570.89,62523.14,52767.72,55311.33,55981.73
Chad,52377,3606529,5108355,65940.17,65835.88,72673.76,71594.68,72282.24
Rwanda,262384,3824085,5477860,70001.38,70138.83,70921.76,73663.69,74839.08
Zimbabwe,252133,3739292,5346770,78366.34,74041.79,75638.88,75919.34,76581.41
Senegal,285090,3922180,5643618,78533.93,91939.14,89017.72,95681.15,95493.82
Guinea,126900,3782145,5431286,91213.40,92803.39,95450.24,98138.87,103262.08
Burkina Faso,328297,3778795,5431243,105051.33,102701.22,107702.27,101855.07,112970.72
Zambia,364201,3892801,5638889,99318.53,96214.00,97728.69,103223.77,101604.27
Tunisia,297036,3602818,5131662,117029.33,128211.41,123778.86,124167.20,127343.17
Benin,68105,3453692,4852820,118050.79,108181.13,117963.59,124771.22,124960.70
Niger,221674,3763737,5384208,108236.65,117834.65,123601.88,126707.58,133982.86
Madagascar,185631,3864258,5619900,128985.32,126674.90,129010.25,131197.73,134576.44
Mali,171969,3469876,4878889,123038.75,132456.58,147324.78,149928.33,159026.42
Mauritania,162520,3222107,4297253,109557.63,61909.99,79872.42,156665.46,157479.95
Mozambique,205488,3830309,5566682,160757.87,158231.17,159924.41,161407.98,164934.05
Malawi,188110,3879389,5600952,173454.86,167989.09,164970.42,181098.71,187366.09
Uganda,329508,3909109,5660301,218142.33,220615.72,202981.34,213950.38,222147.25
Côte d'Ivoire,156969,3934818,5691192,195982.84,211591.29,211439.20,224599.01,227018.00
Angola,9968,3819908,5515088,208584.42,209565.67,214725.32,229159.57,235206.68
Cameroon,46720,3916078,5663196,217630.28,225220.72,231714.36,232030.43,233022.93
Sudan,363216,3534661,4866583,247577.56,230652.54,253197.29,239931.92,268054.39
Kenya,177840,4185637,6211860,255211.01,265506.19,260257.56,264660.66,270916.80
United Republic of Tanzania,305085,3809549,5461092,337430.64,341969.46,333765.86,322616.85,349763.41
Algeria,5252,3532053,5017927,313375.33,324058.40,326007.41,325644.27,341729.98
Ghana,109674,3639339,5135536,308328.59,311092.13,314320.45,337599.06,358915.64
Morocco,199199,3743082,5414999,375977.76,412473.80,367884.18,388495.36,399271.27
Ethiopia,344386,3878162,5598223,415935.50,429139.33,444567.57,448683.76,450788.86
South Africa,282598,3759379,5450983,497289.52,468352.18,462224.16,517590.54,509787.97
Egypt,87792,3996567,5893126,849192.30,868218.73,858568.63,866379.92,852652.92
Nigeria,234366,3954357,5726937,1399542.19,1414362.83,1482945.71,1483268.23,1499774.24